### ISSUE TITLE
Mouse support

### ISSUE THREAD

**Issue by Radiergummi** [bensadeh/circumflex#27]
Wouldn't be strictly necessary, but then again, is reading HN? :) 

It'd be great to be able to click the sections and articles in the list view.

**Comment by bensadeh** [comment]
Hi @Radiergummi 

Thanks for the suggestion, I think this should be easy to add both for Bubble Tea and less!

**Comment by erwin** [comment]
May want to try adding mouse support via Bubblezone

https://github.com/lrstanley/bubblezone/

**Comment by bensadeh** [comment]
Thanks again for the suggestion @Radiergummi. Unfortunately, this proved to be somewhat more complex than I first envisioned. Will close for now and perhaps revisit if mouse support comes directly to Bubble Tea some time in the future.
