### ISSUE TITLE
Error while installing with `go run main.go` from git repo: "package embed is not in GOROOT"

### ISSUE THREAD

**Issue by yusi1** [bensadeh/circumflex#28]
This is the full error:
`bubble/list/list.go:4:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)`

I'm on Debian 11.5 Bullseye with `go` installed from `apt`:
`go 1.15.15 linux/amd64`

This error makes me unable to install the package.

**Comment by bensadeh** [comment]
Thanks for the ticket @yusi1! I am using go 1.19 to build clx, could you update your go to this version to see if that makes it better?

**Comment by bensadeh** [comment]
I am assuming this was a Go version issue, please re-open if not.
