### ISSUE TITLE
Help screen is not overwritten properly

### ISSUE THREAD

**Issue by hkdobrev** [bensadeh/circumflex#29]
<img width="1198" alt="Screenshot 2022-10-14 at 11 26 33" src="https://user-images.githubusercontent.com/506129/195799893-1d986e22-ab2c-4c70-a3ea-bbefaa9b852e.png">

When pressing <kbd>i</kbd> or <kbd>?</kbd>, the screen is redrawn to show the keyboard mappings and other helpful information.

Then pressing <kbd>Esc</kbd> or <kbd>q</kbd> closes the help screen and shows the list of news items again.

But the list of news items is redrawn in such a way that the empty lines do not overwrite the lines from the help screen. The resulting view is a mix of a part of the help screen, often skipping some lines next to the news items.

**Comment by bensadeh** [comment]
Hi @hkdobrev 

This is very strange! Is this happening every time you run `clx`? Can you say a bit more about your system or if you have a way for me to reproduce this?

**Comment by hkdobrev** [comment]
It's happening every time.
I'm using iTerm2 on latest macOS Ventura.
I'll check my custom `less` settings later.

**Comment by bensadeh** [comment]
We have pretty much the same setup, except that I am on Monterey. Maybe this will appear for me as well in Ventura.

**Comment by hkdobrev** [comment]
Latest version is now working fine for me without the help display issue.
