### ISSUE TITLE
Comments not displayed

### ISSUE THREAD

**Issue by msravi** [bensadeh/circumflex#32]
I'm running circumflex on Linux Mint 20.3 (64-bit)

```
~$ uname -a
Linux xxxxx 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

clx was installed using homebrew on linux

The "correct" version of less seems to be in the path

```
  ~$ less --version
  less 608 (PCRE2 regular expressions)
  Copyright (C) 1984-2022  Mark Nudelman
```
When `<enter>` is pressed on any item, it always returns a screen showing 0 comments 0 points, even though there are many comments

![Screenshot_2022-10-14_16-10-54](https://user-images.githubusercontent.com/6314877/195832082-36d2cc3d-3033-49fe-9513-a6872082adf2.png)

Just in case it matters, I've tried it on the kitty terminal (0.25.2) and xfce4-terminal 0.8.10 (Xfce 4.16)

Thank you!

**Comment by JadoJodo** [comment]
I am also seeing this issue using macOS, Alacritty, and nushell.

**Comment by bensadeh** [comment]
Thanks for opening this ticket, I will look into it.

**Comment by bensadeh** [comment]
Are you able to get any results directly from the API through this link? 

https://api.hackerwebapp.com/item/3338485

**Comment by JadoJodo** [comment]
Looks like it's blocked. I'll unblock and try again.

**Comment by breezykermo** [comment]
I am also seeing this issue on Arch. The link you've provided above @bensadeh works in a browser for me.

**Comment by bensadeh** [comment]
@breezykermo Thank you for confirming the link works.

@JadoJodo Any updates on your end?

@msravi Are you able to get any results through the link?

**Comment by msravi** [comment]
Sorry for the delay! Yes, I'm able to see comments in json format through the link.
Looks like the link is filtered by some adblock/tracker lists, but works on unblocking

**Comment by JadoJodo** [comment]
@bensadeh I was seeing the same thing as @msravi ^^

**Comment by bensadeh** [comment]
@msravi Glad it finally works!

@JadoJodo & @breezykermo Is it possible you are having similar issues with blocked endpoints? Are you able to try again from other networks or verify that you are not blocking the endpoints on your end?

**Comment by breezykermo** [comment]
api.hackerwebapp.com doesn't seem to be blocked by any firewall or DNS configuration on my machine as far as I can tell from `ping`/`curl`-ing the URL. Is there a more robust way to check?

**Comment by bensadeh** [comment]
Hmm... Both `ping` and `curl` should do the trick.

I wonder if there is a check on the user agent, as I don't see other differences between calling the endpoint from within `circumflex`and from `curl`. 

@breezykermo Are you able to retry again with this command?

```terminal
curl --user-agent "circumflex/2.6" https://api.hackerwebapp.com/item/3338485
```

**Comment by breezykermo** [comment]
That `curl`command also seems to work without a hitch. Here's an example for reference:

https://user-images.githubusercontent.com/16495856/197407527-5634f90e-9f09-46a2-b002-c908ab2621da.mp4

**Comment by mentalblock** [comment]
Hello, I am also experiencing this issue.

Running the `curl` with the custom user agent returns the data just fine. Again, the curl command that works is:
`curl --user-agent "circumflex/2.6" https://api.hackerwebapp.com/item/3338485`

Removing the agent parameter results in the same HTML reported in the [comment above](https://github.com/bensadeh/circumflex/issues/32#issuecomment-1288163256).

I also use a VPN but I am not sure if that is relevant or a factor in whether Cloudflare does their "security check" as referenced in the HTML.

**Comment by bensadeh** [comment]
Hello @cheeaun, hope it's okay to ping you.

Some of our users are having difficulty getting results from api.hackerwebapp.com. Is there something I can do on my end to get results from your API for these users?

**Comment by cheeaun** [comment]
@bensadeh ok, I've checked the logs on Cloudflare, seems like its "Bot Fight Mode" automatically triggers for `circumflex` UA. I've disabled it now, you can check if it works?

I don't remember _when_ I enabled this feature and it seems difficult for me to backtrace _when_ CF start triggering "JS challenge" page to circumflex. I do remember some time ago, I was trying to prevent search engine bots from spamming the API every second 😅

Sorry! 🙏

**Comment by mentalblock** [comment]
Works perfectly for me now. Thanks all.

**Comment by breezykermo** [comment]
Comments work great for me now. Thanks @cheeaun and @bensadeh for the wonderful tools :)

**Comment by bensadeh** [comment]
Great! Looks like this works now for everyone 😄
