### ISSUE TITLE
Adjust help page contents for different font sizes

### ISSUE THREAD

**Issue by metafates** [bensadeh/circumflex#6]
Awesome app! It would be very nice to adjust contents of the help page on font resize to avoid situations like this
<img width="500" alt="Screenshot 2022-07-15 at 10 58 47" src="https://user-images.githubusercontent.com/62389790/179179830-abcb295e-8c2f-4eb6-8634-ce34a3165086.png">

Or this
<img width="500" alt="Screenshot 2022-07-15 at 10 58 54" src="https://user-images.githubusercontent.com/62389790/179179836-da864cc0-d00a-4af3-b0bc-a684615d8492.png">

**Comment by bensadeh** [comment]
Hi @metafates!

Thank you for the kind words and submitting the issue with screenshots.

I agree that the current view is too brittle when it comes to screen resizes. I think the most compatible approach would be to left align it with a small indent (just like the comment section is).

**Comment by bensadeh** [comment]
Fixed in `2.3`. Thanks again for letting me know!
