### ISSUE TITLE
[request] add a tab with the "best" stories

### ISSUE THREAD

**Issue by m040601** [bensadeh/circumflex#63]
Just stumbled upon this tool and got immediately addicted to it.
Not sure how I missed that post, https://news.ycombinator.com/item?id=33192518
Should have gotten more votes. Your tool is severely underrated.
You should post to hacker news again. 

Same comment as I found there: This is a fantastic case study in great text-only user Interfaces. Rarely do you see someone getting so many details right.

The best TUI hacker news reader I have seen so far. And I have seen a lot.
Thank you very much.

What a nice polished and very well thought interface and default key bindings.
Well documented with even a man page.
Nice of not reinventing a new bloated pager in go, and just making use of the users' $PAGER (less).

Clever use of  "readability" and opening in a clean simple pager.  

github.com/go-shiori/go-readability:

```
This package is based from Readability.js by Mozilla, and written line by line to make sure it looks and works as similar as possible. This way, hopefully all web page that can be parsed by Readability.js are parse-able by go-readability as well.
```

Genius.

I'm not a programmer,  just a proficient terminal user with little understanding of Go. Cant say if this is asking to much.

There is this page, "https://news.ycombinator.com/best" (and https://news.ycombinator.com/classic also)

Could you add an extra tab for that "best" page ?

Thanks in advance.

PS: This is not a request, bu should you ever consider adding a little optionall "bloat" for displaying "images":

This guy, https://github.com/mrusme/reader, also uses go-shiori readability.
In addition he (optionally) uses chafa, https://github.com/hpjansson/chafa/, to display images in the terminal.

The end result is also very polished. 

Well ..., that is, If you like looking at pixelated terminal images like me, a terminal freak.

Maybe there are also "pure" go libraries for doing the same thing chafa does. But I havent seen other robust tools that do a better job for this than chafa or even, https://github.com/dankamongmen/notcurses

**Comment by bensadeh** [comment]
Hi @m040601,

Thank you very nice for your nice words. I've been working on circumflex for close to three years now with relative little feedback, so it is very nice to hear from my users about how they use the tool and what they like.

Adding more categories (like "best") was a feature request I expected would come at some point. I would like to add it in a dynamic way where we can mix and match categories and make it easy to add new ones down the line as well. I can't give an estimated timeline for this feature, but this is something that would be great for circumflex to have.

Thanks for pointing me to pictures in the terminal, it is really useful for reading articles in reader mode. This can be a very nice feature to have as well.

**Comment by bensadeh** [comment]
Hi @m040601 and @jtrv, 

I've added a the "best" category which can be used with the new `--categories` flag. (The "job" category currently has some issues with the Algolia API, so that category is on hold for the time being)

You can add the new category like so:

```console
clx --categories="frontpage,newest,ask,show,best"
```

You can also freely mix and match categories as you please. 

@jtrv: I looked at the examples you linked to in https://github.com/bensadeh/circumflex/issues/76, and the features do look very useful. However, at the moment, I am somewhat at the mercy of the what the [Hacker News API](https://github.com/HackerNews/API) is able to provide.
