### ISSUE TITLE
Add installation instruction for Archlinux to the README

### ISSUE THREAD

**Issue by m040601** [bensadeh/circumflex#64]
We already have two user provided PKGBUILD for Archlinux in the AUR.

- https://aur.archlinux.org/packages/circumflex (release version)
- https://aur.archlinux.org/packages/circumflex-git (latest git master version) 

Trying to get enough votes, so that circumflex could one day make it into an official Archlinux package. In the mean time you can add something like this to the README,

````
# Homebrew
brew install circumflex

# Nix
nix-env -iA nixpkgs.circumflex

# Archlinux
Available on the AUR. Use your favorite AUR helper and choose from:
- https://aur.archlinux.org/packages/circumflex
- https://aur.archlinux.org/packages/circumflex-git
````

**Comment by bensadeh** [comment]
Hi @m040601 ,

Thank you for bringing this to my attention, and thank you to maxjmax for setting this up in the AUR.

Very glad to see this! I'll be glad to update the README as well.

I was wondering if it would be convenient to include the actual commands on how to build it? I am not using Arch or linux, and I wasn't able to gather what it would be, but I was thinking something like this: 

```console
# Arch Linux
# Available on the AUR: https://aur.archlinux.org/packages/circumflex
[command to install circumflex]
```

What do you think?

**Comment by bensadeh** [comment]
Updated the readme, hopefully it’s correct.
