### ISSUE TITLE
Annoying warning relating to `less` command

### ISSUE THREAD

**Issue by jeevatattva** [bensadeh/circumflex#71]
After launching the command, and then, pressing `space` or `enter` on any of the articles, the following warning message shows up -

```
There is no lesskey-src=/var/folders/xy/tn84jnmd3px24klrybplq6w80000gp/T/lesskey3735473353 option ("less --help" for help)
Press RETURN to continue
```

Platform: 
OS: macOS 11.7.6
Circumflex: v2.9.1
less: version 633
shell: zsh 5.8

 ```
$  zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
$
$ type -a less
less is /opt/bin/less    ## version 633 
less is /usr/bin/less    ## version 487 (macOS default)

$ /opt/bin/less --version
less 633 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
$
$ /usr/bin/less --version
less 487 (POSIX regular expressions)
Copyright (C) 1984-2016  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Homepage: http://www.greenwoodsoftware.com/less
```

**Comment by bensadeh** [comment]
Hi jeevatattva and thanks for letting me know about the bug and for showing the output of the commands.

It indeed looks like circumflex is not using the latest version of `less`. However, there is a check at startup that should warn the user if the `less` version is too old.

How are you installing `circumflex` and `less`?

I am a bit perplexed by this because the less version check on startup should pick this up and stop the program. 

What is the output of this command (without the full path)?

```terminal
less --version
```

**Comment by jeevatattva** [comment]
>It indeed looks like circumflex is not using the latest version of less. However, there is a check at startup that should warn the user if the less version is too old.

Removing `less` executable from `/opt/bin`, `circumflex` reports a warning and doesn't even startup.

```sh
❯  clx
Your version of less is outdated

Required: 633
Current:  487

Re-run clx with the --no-less-verify flag to disable this check
```

>How are you installing circumflex and less?

I have `brew` fetched `circumflex` ( `clx` placed in `/opt/bin` ), and built `less` from source.

>I am a bit perplexed by this because the less version check on startup should pick this up and stop the program.

So am I.

>What is the output of this command (without the full path)?

```
❯  less --version
less 633 (PCRE2 regular expressions)
Copyright (C) 1984-2023  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

P.S. - IIRC, there was no warning after launching `clx` until version `2.7`.

**Comment by bensadeh** [comment]
Thanks again for the detailed report. I think we are getting closer to an answer.

What do you get as the output to the following command:

```terminal
less --lesskey-src
```

**Comment by jeevatattva** [comment]
```
❯  less --lesskey-src
There is no lesskey-src option ("less --help" for help)
Missing filename ("less --help" for help)
```
That seems to be the issue, which I remember verifying prior to reporting it here 😮.

Anyway, rebuilt `less` from source, and now the option is available.
```
❯  less  --lesskey-src
Value is required after --lesskey-src
```

Thank you for taking the time to troubleshoot the issue.

**Comment by bensadeh** [comment]
Glad you figured it out!
