### ISSUE TITLE
Chaning NerdFont Icons

### ISSUE THREAD

**Issue by mortymacs** [bensadeh/circumflex#74]
Hi,

I need help loading Nerdfonts. It works for all icons except one of them
![image](https://github.com/bensadeh/circumflex/assets/1261448/2f292a46-e209-4275-b258-0a67b6328922)

I was looking for a way to change the icons but couldn't find the config file.
Do you have any idea how I can do that?

Cheers,
Mort

**Comment by bensadeh** [comment]
Hi @mortymacs!

I am planning to add support for changing both the icons and the colors in the future as a [fix to this issue](https://github.com/bensadeh/circumflex/issues/66).

However, it seems like you're on an older version of circumflex. Can you update to the latest version and let me know if the icon i still malformatted? It is likely related to the Nerd Fonts update to [version 3](https://github.com/ryanoasis/nerd-fonts/blob/master/changelog.md). The latest release of circumflex (2.9.1) has updated all Nerd Fonts to be v3 compatible.

**Comment by mortymacs** [comment]
Hi @bensadeh!

That would be great!

Oh, I didn't check the version :man_facepalming:, I upgraded it, and now it works fine!
![image](https://github.com/bensadeh/circumflex/assets/1261448/50fe3a54-c3c7-4f7f-b59b-5e6f8d5d3d7f)

Thank you very much!

Cheers,
Mort
