### ISSUE TITLE
[Feature Request]: New Tabs & UX Ideas

### ISSUE THREAD

**Issue by jtrv** [bensadeh/circumflex#76]
I'm not sure if you've tried the android app [harmonic](https://play.google.com/store/apps/details?id=com.simon.harmonichackernews&hl=en_US&gl=US), but it has excellent UI/UX. It includes tabs for most upvoted posts posted in the last 24 hours, last 48 hours, and last week as well as tabs for jobs and bookmarked posts. I think these would all be great tabs to add to clx.

[hckernews](https://hckrnews.com/) also has an interesting way of displaying the top 10 or 20 posts for each day with infinite scrolling which could be a nice alternative way to display the feed as well.

**Comment by bensadeh** [comment]
Hi @jtrv and thank you for posting this issue. Looks like this is a popular feature request.

Would you say that this request is similar to the one in this issue: https://github.com/bensadeh/circumflex/issues/63?

**Comment by jtrv** [comment]
yes I just wanted to add extra considerations, maybe we can consolidate these issues.

**Comment by bensadeh** [comment]
Thanks for opening the ticket @jtrv , I left an answer in the linked isue and will close this one for now.
