### ISSUE TITLE
Specifying `less` binary location

### ISSUE THREAD

**Issue by PrayagS** [bensadeh/circumflex#93]
So on macOS, I can see there are multiple distributions of `less` installed,
- `/usr/bin/less` - The GNU `less` that cannot be updated or deleted since the file system is read-only
- `$(brew --prefix)/bin/less` - `less` installed via Homebrew that can be kept updated by the user

Since the circumflex binary uses `exec.Command` directly, it defaults to the GNU `less` and doesn't respect any alias that is set to point to the Homebrew `less`.

Is it a good idea to call `less` in a sub-shell or maybe add a flag to specify the location directly?

Let me know your thoughts. I'd be happy to send a PR.

TIA.

**Comment by bensadeh** [comment]
Hi again @PrayagS !

Hmm, the way the system determines which version of `less` to use is defined by the `PATH` environment variable (colon separated list of paths). If the path to the homebrew binaries is before `/usr/bin/less`, it should choose the one from homebrew first.

What do you get when you run the following two commands:
```console
echo $PATH
which less
```

**Comment by PrayagS** [comment]
Thanks for your prompt response!

And you were right yes. I was prepending new entries in my shell path but they were not reflecting correctly because of macOS things.

More details in case anyone else has this problem: https://gist.github.com/Linerre/f11ad4a6a934dcf01ee8415c9457e7b2. Instead of being prepended, your path entries will be _appended_ if you set those in `.zshenv`.

The order in the shell path is correct after the changes and the homebrew binary is being picked up by circumflex.

Thanks for sharing this quick fix.

**Comment by bensadeh** [comment]
Glad you found a fix for it! 🙌
